### PR TITLE
Update ucaresystem-core - add start snap after snaps Removing old revisions

### PR DESCRIPTION
**Pull request by FrankiePustorino**
Added missing function to restart stopped snaps after the stop and Removing of old revisions

### CODE REVIEW

**Comment by cerebrux** [comment]
@FrankiePustorino thanks a lot ! Everything seems ok and I'll do some preliminary testing and will merge later this weekend

**Comment by cerebrux** [comment]
#42

**Comment by cerebrux** [comment]
Please check the log file I have attached. It tries to restart snaps on a system that doesn't have snap.

P.S. Please test your code in a ubuntu VM before creating a pull request just in case we miss something
[ucare-log.txt](https://github.com/Utappia/uCareSystem/files/15151297/ucare-log.txt)

**Comment by FrankiePustorino** [comment]
Hi  @cerebrux 

I believe we can add this on top of the routine 

```
# Check if 'snap' is installed
if ! command -v snap &>/dev/null; then
    echo "Snap is not installed. Please install it."
    exit 1
fi
```

**Comment by cerebrux** [comment]
> Hi @cerebrux
> 
> I believe we can add this on top of the routine
> 
> ```
> # Check if 'snap' is installed
> if ! command -v snap &>/dev/null; then
>     echo "Snap is not installed. Please install it."
>     exit 1
> fi
> ```

we can't suggest or force user to install something to be able to use it. There are some linux distributions (e.g. Debian, Linux Mint, etc) that do not have snap installed, that is why I have a function to skip it if its not found

**Pull request merged**
